apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: oteldebug
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      filter/oteldebug:
        error_mode: ignore
        traces:
          span:
            - 'attributes["oteldebug"] == nil'
        logs:
          log_record:
            - 'attributes["oteldebug"] == nil'
        metrics:
          metric:
            - 'resource.attributes["oteldebug"] == nil'


    exporters:
      kafka/traces:
        brokers: ["kafka:29092"]
        topic: "otel-traces"
        encoding: "otlp_json"
        protocol_version: "2.0.0"

      kafka/logs:
        brokers: ["kafka:29092"]
        topic: "otel-logs"
        encoding: "otlp_json"
        protocol_version: "2.0.0"

      kafka/metrics:
        brokers: ["kafka:29092"]
        topic: "otel-metrics"
        encoding: "otlp_json"
        protocol_version: "2.0.0"

      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [filter/oteldebug]
          exporters: [debug, kafka/traces]

        logs:
          receivers: [otlp]
          processors: [filter/oteldebug]
          exporters: [debug, debug, kafka/logs]

        metrics:
          receivers: [otlp]
          processors: [filter/oteldebug]
          exporters: [debug, kafka/metrics]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: oteldebug
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
  - port: 4317
    targetPort: 4317
    name: grpc
  - port: 4318
    targetPort: 4318
    name: http
  - port: 8888
    targetPort: 8888
    name: metrics
  selector:
    app: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: oteldebug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.119.0
        command:
        - /otelcol-contrib
        - --config=/etc/otel-collector-config.yaml
        ports:
        - containerPort: 4317
          name: grpc
        - containerPort: 4318
          name: http
        - containerPort: 8888
          name: metrics
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
