apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: oteldebug
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 80
    name: https
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: oteldebug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nochaos/oteldebug-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http

---
kind: Ingress
metadata:
  name: oteldebug-web-ingress
  namespace: oteldebug
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - oteldebug.nochaos.io
    secretName: landing-tls
  rules:
  - host: oteldebug.nochaos.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 443